// lib/utils/pdf-generator.ts
import html2pdf from "html2pdf.js/dist/html2pdf.bundle.min";

interface PDFApplicationData {
  title: string;
  content: string;
  companyName: string;
  opportunityTitle: string;
}

/**
 * Generate and download a PDF from application content
 */
export async function generatePDFFromApplication(
  data: PDFApplicationData
): Promise<void> {
  // Create HTML content for PDF
  const htmlContent = `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="UTF-8">
        <style>
          body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 8.5in;
            margin: 0.5in;
            padding: 0;
          }
          .header {
            margin-bottom: 2rem;
            border-bottom: 2px solid #0066cc;
            padding-bottom: 1rem;
          }
          .title {
            font-size: 24px;
            font-weight: bold;
            color: #0066cc;
            margin: 0 0 0.5rem 0;
          }
          .meta {
            font-size: 12px;
            color: #666;
            margin: 0;
          }
          .content {
            font-size: 11px;
            line-height: 1.8;
            color: #333;
            white-space: pre-wrap;
            word-wrap: break-word;
          }
          .footer {
            margin-top: 2rem;
            padding-top: 1rem;
            border-top: 1px solid #ddd;
            font-size: 10px;
            color: #999;
            text-align: center;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <p class="title">${escapeHtml(data.title)}</p>
          <p class="meta">Company: ${escapeHtml(data.companyName)} | Position: ${escapeHtml(data.opportunityTitle)}</p>
        </div>
        <div class="content">${escapeHtml(data.content)}</div>
        <div class="footer">
          <p>Generated by Smart Apply AI • ${new Date().toLocaleDateString()}</p>
        </div>
      </body>
    </html>
  `;

  const element = document.createElement("div");
  element.innerHTML = htmlContent;

  const options = {
    margin: [0.5, 0.5, 0.5, 0.5],
    filename: `Application_${data.opportunityTitle.replace(/\s+/g, "_")}_${new Date().getTime()}.pdf`,
    image: { type: "jpeg", quality: 0.98 },
    html2canvas: { scale: 2 },
    jsPDF: { unit: "in", format: "letter", orientation: "portrait" },
  };

  return html2pdf().set(options).from(element).save();
}

/**
 * Escape HTML special characters
 */
function escapeHtml(text: string): string {
  const div = document.createElement("div");
  div.textContent = text;
  return div.innerHTML;
}
