// lib/utils/pdf-generator.ts
import html2pdf from "html2pdf.js/dist/html2pdf.bundle.min";

interface PDFApplicationData {
  title: string;
  content: string;
  companyName: string;
  opportunityTitle: string;
}

/**
 * Generate and download a PDF from application content
 */
export async function generatePDFFromApplication(
  data: PDFApplicationData
): Promise<void> {
  return new Promise((resolve, reject) => {
    try {
      // Create HTML content for PDF
      const htmlContent = `
        <!DOCTYPE html>
        <html>
          <head>
            <meta charset="UTF-8">
            <style>
              body {
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                line-height: 1.6;
                color: #333;
                max-width: 8.5in;
                margin: 0.5in;
                padding: 0;
              }
              .header {
                margin-bottom: 2rem;
                border-bottom: 2px solid #0066cc;
                padding-bottom: 1rem;
              }
              .title {
                font-size: 24px;
                font-weight: bold;
                color: #0066cc;
                margin: 0 0 0.5rem 0;
              }
              .meta {
                font-size: 12px;
                color: #666;
                margin: 0;
              }
              .content {
                font-size: 11px;
                line-height: 1.8;
                color: #333;
                white-space: pre-wrap;
                word-wrap: break-word;
              }
              .footer {
                margin-top: 2rem;
                padding-top: 1rem;
                border-top: 1px solid #ddd;
                font-size: 10px;
                color: #999;
                text-align: center;
              }
            </style>
          </head>
          <body>
            <div class="header">
              <p class="title">${escapeHtml(data.title)}</p>
              <p class="meta">Company: ${escapeHtml(data.companyName)} | Position: ${escapeHtml(data.opportunityTitle)}</p>
            </div>
            <div class="content">${escapeHtml(data.content)}</div>
            <div class="footer">
              <p>Generated by Smart Apply AI • ${new Date().toLocaleDateString()}</p>
            </div>
          </body>
        </html>
      `;

      const element = document.createElement("div");
      element.innerHTML = htmlContent;

      // Append to body to ensure styles are applied and it's renderable
      element.style.position = 'absolute';
      element.style.left = '-9999px';
      element.style.top = '0';
      document.body.appendChild(element);

      const filename = `Application_${data.opportunityTitle.replace(/\s+/g, "_")}_${new Date().getTime()}.pdf`;

      const options = {
        margin: [0.5, 0.5, 0.5, 0.5],
        filename: filename,
        image: { type: "jpeg", quality: 0.98 },
        html2canvas: { scale: 2, useCORS: true, allowTaint: true },
        jsPDF: { unit: "in", format: "letter", orientation: "portrait" },
      };

      html2pdf()
        .set(options)
        .from(element)
        .save()
        .then(() => {
          console.log("PDF generated successfully:", filename);
          document.body.removeChild(element);
          resolve();
        })
        .catch((error: any) => {
          console.error("PDF generation error:", error);
          if (document.body.contains(element)) {
            document.body.removeChild(element);
          }
          reject(new Error("Failed to generate PDF. Please try again."));
        });
    } catch (error) {
      console.error("Unexpected error in PDF generation:", error);
      reject(new Error("An unexpected error occurred while generating the PDF."));
    }
  });
}

/**
 * Escape HTML special characters
 */
function escapeHtml(text: string): string {
  const div = document.createElement("div");
  div.textContent = text;
  return div.innerHTML;
}
